# Generated by Django 4.1.2 on 2022-11-22 04:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_gallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
