# Generated by Django 4.1.2 on 2022-11-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_gallerypage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceslandingpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='serviceslandingpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='serviceslandingpage',
            name='reverse_header',
        ),
    ]
