# Generated by Django 4.1.2 on 2022-11-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_gallerypage_header_image_gallerypage_reverse_header_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
