# Generated by Django 4.1.2 on 2022-11-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_gallerypage_header_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
