# Generated by Django 4.1.2 on 2022-11-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
