# Generated by Django 4.1.2 on 2022-10-22 21:54

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_carousel',
            field=wagtail.fields.StreamField([('carousel_item', wagtail.images.blocks.ImageChooserBlock(required=True))], null=True, use_json_field=None),
        ),
    ]
