# Generated by Django 4.1.2 on 2022-10-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_serviceslandingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesLandingPage',
        ),
    ]
