# Generated by Django 4.1.2 on 2022-11-06 19:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StreamBlock([('free_text', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'h5', 'bold', 'underline', 'italic', 'ol', 'ul', 'hr', 'lead-in', 'link', 'button-link', 'link-list', 'document-link', 'image', 'embed'], required=True))])), ('link_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.CharBlock())]))]))], null=True, use_json_field=None),
        ),
    ]
