# Generated by Django 4.1.2 on 2022-11-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_aboutpage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='reverse_header',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
