# Generated by Django 4.1.2 on 2022-11-23 05:55

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallerypage',
            name='images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=False),
        ),
    ]
