# Generated by Django 4.1.2 on 2022-11-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallerylandingpage_header_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerylandingpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='gallerylandingpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='gallerylandingpage',
            name='reverse_header',
        ),
        migrations.RemoveField(
            model_name='gallerypostpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='gallerypostpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='gallerypostpage',
            name='reverse_header',
        ),
    ]
